services:
  - type: web
    name: berdawni-backend
    runtime: node
    buildCommand: cd backend && npm install
    startCommand: cd backend && node app.js
    envVars:
      - key: CONNECTION_URL_NEW_DEV
        sync: false
      - key: CLOUDINARY_CLOUD_NAME
        value: berdawniwater
      - key: CLOUDINARY_API_KEY
        value: 948888722679467
      - key: CLOUDINARY_API_SECRET
        sync: false
  - type: web
    name: berdawni-frontend
    runtime: static
    buildCommand: echo "No build needed"
    staticPublishPath: frontend/dist/berdawni-front-end
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
